// <auto-generated />
using System;
using InvestmentPerformanceWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestmentPerformanceWebAPI.Migrations
{
    [DbContext(typeof(InvestmentDbContext))]
    partial class InvestmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("InvestmentPerformanceWebAPI.Models.Investment", b =>
                {
                    b.Property<int>("InvestmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostBasisPerShare")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NumberOfShares")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeOfPurchase")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InvestmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Investments");

                    b.HasData(
                        new
                        {
                            InvestmentId = 1,
                            CostBasisPerShare = 120.00m,
                            CurrentPrice = 175.00m,
                            Name = "Apple Inc.",
                            NumberOfShares = 10m,
                            Ticker = "AAPL",
                            TimeOfPurchase = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            InvestmentId = 2,
                            CostBasisPerShare = 220.00m,
                            CurrentPrice = 200.00m,
                            Name = "Tesla Motors",
                            NumberOfShares = 5m,
                            Ticker = "TSLA",
                            TimeOfPurchase = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            InvestmentId = 3,
                            CostBasisPerShare = 95.00m,
                            CurrentPrice = 130.00m,
                            Name = "Amazon.com",
                            NumberOfShares = 8m,
                            Ticker = "AMZN",
                            TimeOfPurchase = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("InvestmentPerformanceWebAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Name = "Alice"
                        },
                        new
                        {
                            UserId = 2,
                            Name = "Bob"
                        });
                });

            modelBuilder.Entity("InvestmentPerformanceWebAPI.Models.Investment", b =>
                {
                    b.HasOne("InvestmentPerformanceWebAPI.Models.User", "User")
                        .WithMany("Investments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InvestmentPerformanceWebAPI.Models.User", b =>
                {
                    b.Navigation("Investments");
                });
#pragma warning restore 612, 618
        }
    }
}
